Algoritmo "tela de boot"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2026
Var
contador: inteiro
carregamento: vetor [0..10] de inteiro


Inicio
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("")
escreval("LógicaOS")
escreval("Carregando...")
enquanto (carregamento[contador]<10) faca
contador <- contador+1
carregamento[contador] <- contador+1
escreva(carregamento[contador])
fimenquanto
escreval("")
escreval("Sistema pronto")
limpatela
Fimalgoritmo